/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export * as factories from './factories';
export { InfoContract__factory } from './factories/InfoContract__factory';
export type { InfoContract } from './InfoContract';
